### ISSUE TITLE
detailedDiff returning confusing data

### ISSUE THREAD

**Issue by sdetweil** [mattphillips/deep-object-diff#62]
i look at the results of the diff and see 
```
{added:{}, deleted:{}, updated:{}}
```
I compare against an object like that, and get not equal.

I json.stringify() the object and it looks the same
I check the number of keys in each section and see some number of keys in one of more areas (usually deleted)
but those keys are not in the object being compared. 

BUT   
I compare this object (old) 
```
{
		compliments: {
			anytime: ["Hey there sexy!"],
			morning: ["Good morning, handsome!", "Enjoy your day!", "How was your sleep?"],
			afternoon: ["Hello, beauty!", "You look sexy!", "Looking good today!"],
			evening: ["Wow, you look hot!", "You look nice!", "Hi, sexy!"],
			"....-01-01": ["Happy new year!"]
		},
		updateInterval: 30000,
		remoteFile: null,
		fadeSpeed: 4000,
		morningStartTime: 3,
		morningEndTime: 12,
		afternoonStartTime: 12,
		afternoonEndTime: 17,
		random: true,
		mockDate: null
	}
```
against this (new) 
```
compliments: {
            anytime: [
              "Hey there sexy!"
            ],
            morning: [
              "Good morning, handsome!",
              "Enjoy your day!",
              "How was your sleep?"
            ],
            afternoon: [
              "Hello, beauty!",
              "You look sexy!",
              "Looking good today!"
            ],
            evening: [
              "Wow, you look hot!",
              "You look nice!",
              "Hi, sexy!"
            ],
            "-01-01": [
              "Happy new year!"
            ]
          },
          updateInterval: 30000,
          fadeSpeed: 4000,
          morningStartTime: 3,
          morningEndTime: 12,
          afternoonStartTime: 12,
          afternoonEndTime: 17,
          random: true
        }
```        
and get this 
```
{
  "added": {
    "compliments": {
      "-01-01": [
        "Happy new year!"
      ]
    }
  },
  "deleted": {
    "compliments": {}
  },
  "updated": {}
```

but deleted is incomplete
"....-01-01" is not there

note this text is presented by JSON.stringify() on the objects..

**Comment by anko** [comment]
Could you post a minimal example of runnable code that demonstrates the problem?

I tried this—

```js
const { detailedDiff } = require('deep-object-diff')

const prev = { '....-01-01': ['Happy new year!'] }
const next = { '-01-01': ['Happy new year!'] }

console.log(detailedDiff(prev, next))
```

—and its output seems correct:

```
{
  added: { '-01-01': [ 'Happy new year!' ] },
  deleted: { '....-01-01': undefined },
  updated: {}
}
```

- - -

I also tried the same snippet as above but copy-pasted your objects.  I got this output, which also seems correct logically, but it's very different from your result:

```
{
  added: { compliments: { '-01-01': [Array] } },
  deleted: {
    compliments: { '....-01-01': undefined },
    remoteFile: undefined,
    mockDate: undefined
  },
  updated: {}
}
```

**Comment by sdetweil** [comment]
here you go...

**Comment by anko** [comment]
I think I see what's going on.  `JSON.stringify` ignores properties that are `undefined`, because they are not allowed in valid JSON according to [the spec](https://tools.ietf.org/html/rfc7159#section-3):
 
> A JSON value MUST be an object, array, number, or string, or one of the following three literal names:
>
>      false null true

`undefined` is not included, so `JSON.stringify({ x: undefined })` evaluates to `'{}'`.

If you must get the diff output into JSON format specifically, you'll have to transform it such that `undefined` isn't used.

If you don't need valid JSON but just want to turn the object into a representative string for debugging purposes, consider [`util.inspect`](https://nodejs.org/api/util.html#util_util_inspect_object_options), which can stringify any JavaScript value, but not in a way that `JSON.parse` can necessarily read back in.

**Comment by sdetweil** [comment]
I guess the point is that the OLD object DOES have the definition.. so it shouldn't be undefined.. 
yes, its not in the new , but,.. it WAS in the old..

**Comment by anko** [comment]
Every value in the `deleted` part of a `detailedDiff` is `undefined`, and [the documentation examples show this](https://github.com/mattphillips/deep-object-diff#detaileddiff).  It's expected behaviour.

I think `undefined` makes sense.  An entry's value after deletion is `undefined` as listed in its the `deleted` entry, just as an entry's value after addition is the one listed in the corresponding `added` entry.

**Comment by sdetweil** [comment]
working as designed, but not right..
